<a href="https://colab.research.google.com/github/aquangnguyen1992/Advanced_Data_Science_Capstone/blob/master/Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Get the dataset from Kaggle***

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/gdrive/My Drive/Kaggle"
!kaggle competitions download -c ieee-fraud-detection
!unzip \*.zip  && rm *.zip

 81% 42.0M/52.2M [00:00<00:00, 37.2MB/s]
100% 52.2M/52.2M [00:00<00:00, 59.7MB/s]
  0% 0.00/1.14M [00:00<?, ?B/s]
100% 1.14M/1.14M [00:00<00:00, 35.2MB/s]
  0% 0.00/3.21M [00:00<?, ?B/s]
100% 3.21M/3.21M [00:00<00:00, 104MB/s]
 89% 52.0M/58.3M [00:01<00:00, 37.4MB/s]
100% 58.3M/58.3M [00:01<00:00, 54.7MB/s]
  0% 0.00/3.26M [00:00<?, ?B/s]
100% 3.26M/3.26M [00:00<00:00, 106MB/s]
Archive:  sample_submission.csv.zip
  inflating: sample_submission.csv   

Archive:  test_identity.csv.zip
  inflating: test_identity.csv       

Archive:  train_transaction.csv.zip
  inflating: train_transaction.csv   

Archive:  train_identity.csv.zip
  inflating: train_identity.csv      

Archive:  test_transaction.csv.zip
  inflating: test_transaction.csv    

5 archives were successfully processed.


# ***Analyzing the dataset***

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [6]:
os.chdir("/content")
dataset_transaction = pd.read_csv('train_transaction.csv')
dataset_transaction.head(5)

TransactionID  isFraud  TransactionDT  ...  V337 V338  V339
0        2987000        0          86400  ...   NaN  NaN   NaN
1        2987001        0          86401  ...   NaN  NaN   NaN
2        2987002        0          86469  ...   NaN  NaN   NaN
3        2987003        0          86499  ...   NaN  NaN   NaN
4        2987004        0          86506  ...   0.0  0.0   0.0

[5 rows x 394 columns]

In [7]:
dataset_identity = pd.read_csv('train_identity.csv')
dataset_identity.head(5)

TransactionID  id_01  ...  DeviceType                     DeviceInfo
0        2987004    0.0  ...      mobile  SAMSUNG SM-G892A Build/NRD90M
1        2987008   -5.0  ...      mobile                     iOS Device
2        2987010   -5.0  ...     desktop                        Windows
3        2987011   -5.0  ...     desktop                            NaN
4        2987016    0.0  ...     desktop                          MacOS

[5 rows x 41 columns]

In [8]:
dataset_identity.columns

Index(['TransactionID', 'id_01', 'id_02', 'id_03', 'id_04', 'id_05', 'id_06',
       'id_07', 'id_08', 'id_09', 'id_10', 'id_11', 'id_12', 'id_13', 'id_14',
       'id_15', 'id_16', 'id_17', 'id_18', 'id_19', 'id_20', 'id_21', 'id_22',
       'id_23', 'id_24', 'id_25', 'id_26', 'id_27', 'id_28', 'id_29', 'id_30',
       'id_31', 'id_32', 'id_33', 'id_34', 'id_35', 'id_36', 'id_37', 'id_38',
       'DeviceType', 'DeviceInfo'],
      dtype='object')

In [9]:
dataset_transaction.columns

Index(['TransactionID', 'isFraud', 'TransactionDT', 'TransactionAmt',
       'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5',
       ...
       'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338',
       'V339'],
      dtype='object', length=394)

In [11]:
float_columns = dataset_transaction.columns[np.where(dataset_transaction.dtypes == np.dtype('float64'))]
int_columns = dataset_transaction.columns[np.where(dataset_transaction.dtypes == np.dtype('int64'))]
obj_columns = dataset_transaction.columns[np.where(dataset_transaction.dtypes == np.dtype('O'))]

In [18]:
# Detect the columns with NaN and code it with an extra features
for column in float_columns:
  if np.any(np.isnan(dataset_transaction[column].values)):
    dataset_transaction[column].astype('float16')
    dataset_transaction[column + "_NaN_Code"] = np.isnan(dataset_transaction[column].values).astype('int8')
    dataset_transaction.loc[np.where(np.isnan(dataset_transaction[column].values))[0], column] = 0.0

In [20]:
for column in int_columns:
  if np.any(np.isnan(dataset_transaction[column].values)):
    dataset_transaction[column].astype('int32')
    dataset_transaction[column + "_NaN_Code"] = np.isnan(dataset_transaction[column].values).astype('int8')
    dataset_transaction.loc[np.where(np.isnan(dataset_transaction[column].values))[0], column] = 0

In [21]:
dataset_transaction.head(5)

TransactionID  isFraud  ...  V338_NaN_Code  V339_NaN_Code
0        2987000        0  ...              1              1
1        2987001        0  ...              1              1
2        2987002        0  ...              1              1
3        2987003        0  ...              1              1
4        2987004        0  ...              0              0

[5 rows x 755 columns]

In [29]:
from sklearn.preprocessing import OneHotEncoder
for column in obj_columns:
  ohc = OneHotEncoder()
  dataset_transaction.loc[np.where(dataset_transaction[column].isnull())[0], column] = 'Null'
  encoded = ohc.fit_transform(dataset_transaction[column].values.reshape(-1,1)).toarray()    
  pd_encoded = pd.DataFrame(encoded, columns=[column+"_"+str(i) for i in range np.unique(dataset_transaction[])])


ProductCD
card4


TypeError: ignored

In [36]:
np.unique(dataset_transaction['card4'])

(array([], dtype=int64),)

In [60]:
index_1 = np.where(dataset_transaction['card4'] == 'mastercard')
index_2 = np.where(dataset_transaction['card4'] == 'discover')
index_3 = np.where(dataset_transaction['card4'] == 'visa')
index_4 = np.where(dataset_transaction['card4'] == 'american express')
index = np.hstack((index_1[0], index_2[0], index_3[0], index_4[0]))

In [66]:
for i in range(len(dataset_transaction)):
  if i not in index:
    print(dataset_transaction.loc[i,'card4'], dataset_transaction.loc[i,'card4'] == 'nan')

nan False
nan False
nan False


KeyboardInterrupt: ignored

In [69]:
from sklearn.preprocessing import OneHotEncoder
ohc = OneHotEncoder()
dataset_transaction.loc[np.where(dataset_transaction['card4'].isnull())[0], 'card4'] = 'Null'
encoded = ohc.fit_transform(dataset_transaction['card4'].values.reshape(-1,1)).toarray()


In [70]:
print(encoded)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
